import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const contentDir = path.join(root, 'content');
const chaptersDir = path.join(contentDir, 'chapters');
const outDir = path.join(root, 'src', 'generated');
const outFile = path.join(outDir, 'book-data.js');

const book = JSON.parse(await readFile(path.join(contentDir, 'book.json'), 'utf8'));
const chapterFiles = (await readdir(chaptersDir)).filter((name) => name.endsWith('.md')).sort();
const contentBySource = new Map();

await Promise.all(
  chapterFiles.map(async (fileName) => {
    const source = `content/chapters/${fileName}`;
    const markdown = await readFile(path.join(chaptersDir, fileName), 'utf8');
    contentBySource.set(source, markdown);
  }),
);

const knownSources = new Set();
const chapters = [];

for (const part of book.parts ?? []) {
  for (const chapter of part.chapters ?? []) {
    const markdown = contentBySource.get(chapter.source) ?? '';
    knownSources.add(chapter.source);
    chapters.push({
      ...chapter,
      partId: part.id,
      partTitle: part.title,
      hasContent: markdown.trim().length > 0,
      markdown,
    });
  }
}

const extraChapters = [];
for (const [source, markdown] of contentBySource.entries()) {
  if (knownSources.has(source)) continue;
  const id = path.basename(source, '.md');
  const title = markdown.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? id;
  extraChapters.push({
    id,
    order: id.match(/^\d+/)?.[0] ?? '',
    title,
    level: '新增',
    status: 'draft',
    tags: ['新增章节'],
    source,
    summary: ['该章节尚未写入 content/book.json，已由构建脚本自动发现。'],
    partId: 'part-extra',
    partTitle: '自动发现的章节',
    hasContent: markdown.trim().length > 0,
    markdown,
  });
}

const generatedBook = {
  ...book,
  parts: [
    ...(book.parts ?? []),
    ...(extraChapters.length
      ? [
          {
            id: 'part-extra',
            title: '自动发现的章节',
            chapters: extraChapters.map(({ markdown, hasContent, partId, partTitle, ...chapter }) => chapter),
          },
        ]
      : []),
  ],
  chapters: [...chapters, ...extraChapters],
  generatedAt: new Date().toISOString(),
};

await mkdir(outDir, { recursive: true });
await writeFile(
  outFile,
  `// This file is generated by scripts/build-content.mjs. Do not edit by hand.\nexport const bookData = ${JSON.stringify(generatedBook, null, 2)};\n`,
);

console.log(`Generated ${path.relative(root, outFile)} with ${generatedBook.chapters.length} chapters.`);
